// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMOblx0B26x7955puGCNOHVNMObo0VlOs',
    appId: '1:708553975278:web:0ef9d7bfbc3a4d60541aff',
    messagingSenderId: '708553975278',
    projectId: 'splitwise-b6fc9',
    authDomain: 'splitwise-b6fc9.firebaseapp.com',
    storageBucket: 'splitwise-b6fc9.firebasestorage.app',
    measurementId: 'G-NKHST4L3F6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQEmOOOtlxjB3_ve4W1M18LbGKAbjP7HE',
    appId: '1:708553975278:android:4174a2c7e663dde8541aff',
    messagingSenderId: '708553975278',
    projectId: 'splitwise-b6fc9',
    storageBucket: 'splitwise-b6fc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8LZxNLplFTXQ4uVibQ8p-kpPi6EC2B0s',
    appId: '1:708553975278:ios:d0887f01abcf1c02541aff',
    messagingSenderId: '708553975278',
    projectId: 'splitwise-b6fc9',
    storageBucket: 'splitwise-b6fc9.firebasestorage.app',
    iosBundleId: 'com.example.splitwiseClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8LZxNLplFTXQ4uVibQ8p-kpPi6EC2B0s',
    appId: '1:708553975278:ios:d0887f01abcf1c02541aff',
    messagingSenderId: '708553975278',
    projectId: 'splitwise-b6fc9',
    storageBucket: 'splitwise-b6fc9.firebasestorage.app',
    iosBundleId: 'com.example.splitwiseClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMOblx0B26x7955puGCNOHVNMObo0VlOs',
    appId: '1:708553975278:web:d73ab4598ac90c11541aff',
    messagingSenderId: '708553975278',
    projectId: 'splitwise-b6fc9',
    authDomain: 'splitwise-b6fc9.firebaseapp.com',
    storageBucket: 'splitwise-b6fc9.firebasestorage.app',
    measurementId: 'G-Y3W5J4JPTE',
  );
}
